export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_REVIEW_TEXT = 'CHANGE_REVIEW_TEXT';
export const CHANGE_RATING = 'CHANGE_RATING';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW_PAGES = 'GET_REVIEW_PAGES';
